// Extracts only the generated package into a private test directory and uses its bundled runtime.
import assert from 'node:assert/strict';import {mkdir,readFile,rm} from 'node:fs/promises';import {randomUUID,createHash} from 'node:crypto';import {resolve,join,basename} from 'node:path';import {pathToFileURL} from 'node:url';import {execFile} from 'node:child_process';import {promisify} from 'node:util';import {liveLaunch} from '../../src/server/lifecycle.mjs';
const exec=promisify(execFile),[playwright,archive]=process.argv.slice(2),workspace=resolve('.vide','package-check',randomUUID()),install=join(workspace,'install space'),data=join(workspace,'data');
await mkdir(install,{recursive:true});await mkdir(data);await exec('tar.exe',['-xf',resolve(archive),'-C',install],{windowsHide:true});
const packageRoot=join(install,basename(archive,'.zip')),manifest=JSON.parse(await readFile(join(packageRoot,'package-manifest.json'),'utf8'));
for(const file of manifest.files){const path=resolve(packageRoot,file.path);assert.ok(path.startsWith(packageRoot+'\\'));assert.equal(createHash('sha256').update(await readFile(path)).digest('hex'),file.sha256);}
const env={...process.env,VIDE_DATA_DIR:data,VIDE_PORT:'0',PATH:join(process.env.WINDIR,'System32')};delete env.VIDE_CODEX_PATH;delete env.VIDE_CLAUDE_PATH;
const launch=()=>exec(join(packageRoot,'VIDE.exe'),['--no-browser'],{env,windowsHide:true,timeout:15000});
const waitUrl=async()=>{const deadline=Date.now()+15000;while(Date.now()<deadline){const url=await liveLaunch(data);if(url)return url;await new Promise(resolve=>setTimeout(resolve,50));}throw Error('Package startup timed out');};
const {chromium}=await import(pathToFileURL(playwright).href);let browser;
try{
 await launch();let url=await waitUrl();browser=await chromium.launch({channel:'chrome',headless:true,args:['--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(url);await page.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('연결됨'));assert.equal(await page.locator('#canvas canvas').count(),1);await page.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('ChatGPT 연결됨'),null,{timeout:20000});
 const projectId=await page.evaluate(async()=>{const {api}=await import('/gateway.mjs');return (await api('/projects','POST',{name:'Portable preserved project'})).id;});await launch();assert.equal(await waitUrl(),url);
 await page.getByLabel('초안 메뉴').click();page.once('dialog',dialog=>dialog.accept());await page.getByRole('button',{name:'앱 종료',exact:true}).click();await page.getByText('VIDE 종료 중입니다. 이 창을 닫아도 됩니다.',{exact:true}).waitFor();
 const deadline=Date.now()+10000;while(await liveLaunch(data)){if(Date.now()>deadline)throw Error('Shutdown timed out');await new Promise(resolve=>setTimeout(resolve,40));}
 await launch();url=await waitUrl();await page.goto(url);await page.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('연결됨'));const projects=await page.evaluate(async()=>{const {api}=await import('/gateway.mjs');return api('/projects');});assert.ok(projects.some(project=>project.id===projectId));assert.deepEqual(errors,[]);
 await page.evaluate(async()=>{const {api}=await import('/gateway.mjs');await api('/shutdown','POST',{});});while(await liveLaunch(data))await new Promise(resolve=>setTimeout(resolve,40));
 const backup=join(workspace,'saved backup'),runtime=join(packageRoot,'runtime','node.exe'),backupScript=join(packageRoot,'app','src','desktop','backup.mjs');await exec(runtime,[backupScript,'create',data,backup],{env,windowsHide:true});const verification=JSON.parse((await exec(runtime,[backupScript,'verify',backup],{env,windowsHide:true})).stdout);assert.ok(verification.verified);
 assert.ok(resolve(install).startsWith(workspace+'\\'));await rm(install,{recursive:true,force:true,maxRetries:20,retryDelay:100});assert.ok((await readFile(join(data,'vide.sqlite'))).length>0);
 console.log(JSON.stringify({bundledRuntime:true,filesVerified:manifest.files.length,spaceInPath:true,duplicateLaunch:true,browserLoaded:true,restarted:true,dataPreservedAfterRemoval:true,offlineBackupVerified:true,isolatedData:data}));
}finally{if(browser)await browser.close();const url=await liveLaunch(data);if(url){const origin=new URL(url).origin;const auth=await fetch(origin+'/api/v1/session',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({token:new URL(url).hash.slice(1)})});await fetch(origin+'/api/v1/shutdown',{method:'POST',headers:{Origin:origin,Cookie:auth.headers.get('set-cookie').split(';')[0],'Content-Type':'application/json'},body:'{}'});}}
